---
title: "Exploring datasets from television show 'Alone'"
output: html_document
date: "2024-03-24"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load data

```{r, include =FALSE}
library(tidyverse)
library(widyr)

theme_set(theme_light())

survivalists <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-24/survivalists.csv')
loadouts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-24/loadouts.csv')
episodes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-24/episodes.csv')
seasons <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-24/seasons.csv')

survivalists_processed <- survivalists %>%
  mutate(state = as.factor(state),
         season = as.integer(season),
         country = as.factor(country))


season_survivalists <- survivalists_processed %>%
  inner_join(seasons, by = "season") %>%
  as_tibble()

```

# Where are contestants on the show from?

```{r "Contestants"}

survivalists_processed %>%
  group_by(state) %>%
  count(state, sort = TRUE) %>%
  ungroup() %>%
  filter(state != is.na(state),
         n >= 2) %>%
  mutate(state = fct_reorder(state, n)) %>%
  ggplot(aes(state, n)) +
  geom_col() +
  coord_flip() +
  labs(title = "Where do contestants reside?",
       subtitle = "States/provinces with at least two contestants",
       x = "State/Province",
       y = "Number of contestants")

```


# How long do contestants usually last?
## A look into the distribution of days lasted overall and also looking into days lasted by location.

```{r "View of days lasted"}
season_survivalists %>%
  ggplot(aes(days_lasted, fill = gender)) +
  geom_histogram(bins = 11) +
  scale_y_continuous(limits = c(0,16), breaks = c(seq(0,16, by = 2)))



season_survivalists %>%
  mutate(location = fct_reorder(location, days_lasted)) %>%
  ggplot(aes(location, days_lasted)) + 
  geom_boxplot() + 
  coord_flip() +
  labs(x = "Location",
       y = "Days Lasted",
       title = "Distribution of days lasted by location")



```

# What gear do contestants choose to bring with them?

```{r}
loadouts %>%
  count(item, sort = TRUE) %>%
  mutate(item = fct_reorder(item, n)) %>%
  ggplot(aes(item, n)) +
  geom_col() +
  coord_flip() +
  labs(title = "Most commonly picked gear in nine seasons of Alone", 
       subtitle = "Each contestant chooses ten items to bring with them", 
       x = "Item", 
       y = "Number of times chosen for loadout")


```


# How has Alone performed over the first eight seasons?

```{r}



episodes %>%
  group_by(season) %>%
  summarize(avg_rating = mean(imdb_rating),
            total_ratings = sum(n_ratings)) %>%
  arrange(desc(avg_rating)) %>%
  filter(avg_rating != is.na(avg_rating),
         season != 8) %>%
  ggplot(aes(season, avg_rating)) +
  geom_line() +
  geom_point(aes(size = total_ratings), show.legend = FALSE) +
  scale_x_continuous(limits = c(1,7.5), breaks = c(seq(0,8, by = 1))) +
  scale_y_binned() +
  labs(x = "Season",
       y = "IMDB Rating",
       title = "Average IMDB rating of each season",
       subtitle = "Point size displays total number of ratings per season")

  


episodes %>%
  filter(viewers != is.na(viewers),
         season != 8) %>%
  group_by(season) %>%
  summarize(total_viewership = sum(viewers)) %>%
  arrange(desc(total_viewership)) %>%
  ggplot(aes(season, total_viewership) ) +
  geom_line() +
  scale_x_continuous(limits = c(1,7), breaks = c(seq(0,7, by = 1))) +
  scale_y_continuous(limits = c(12,22), breaks = c(seq(12,22, by = 2))) +
  labs(x = "Season",
       y = "Total Viewership (Millions)")




```

